export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const CLOSE_DROPDOWN = "CLOSE_DROPDOWN";
export const OPEN_DROPDOWN = "OPEN_DROPDOWN";
export const CHANGE_HEADING = "CHANGE_HEADING";
export const OPEN_TOP_DRAWER = "OPEN_TOP_DRAWER";
export const CLOSE_TOP_DRAWER = "CLOSE_TOP_DRAWER";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const ERROR = "ERROR";
export const ADD_PATIENT = "ADD_PATIENT";
export const GET_PATIENT_BY_ID = "GET_PATIENT_BY_ID";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const GET_ALL_PATIENTS = "GET_ALL_PATIENTS";
export const GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const GET_APPOINTMENT = "ADD_APPOINTMENT";
export const ADD_TREATMENT = "ADD_TREATMENT";
export const GET_TREATMENTS = "GET_TREATMENTS";
export const LOGOUT = "LOGOUT";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const GET_FEEDBACK = "GET_FEEDBACK";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const UPDATE_PATIENT_DETAILS = "UPDATE_PATIENT_DETAILS";
export const UPDATE_APPOINTMENT_DETAILS = "UPDATE_APPOINTMENT_DETAILS";
export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
export const EDIT_PATIENT = "EDIT_PATIENT";
export const ADD_INVOICE = "ADD_INVOICE";
export const GET_INVOICE_BY_PATIENT_ID = "GET_INVOICE_BY_PATIENT_ID";
export const GET_ALL_EXERCISES = "GET_ALL_EXERCISES";
export const GET_EXERCISE_BY_ID = "GET_EXERCISE_BY_ID";
export const ADD_EXERCISE = "ADD_EXERCISE";



export const ADD_DEMOGRAPHIC_DATA = "ADD_DEMOGRAPHIC_DATA";
export const GET_DEMOGRAPHIC_DATA = "GET_DEMOGRAPHIC_DATA";
export const GET_DEMOGRAPHIC_DATA_BY_ID = "GET_DEMOGRAPHIC_DATA_BY_ID";


export const ADD_MOTOR_DATA = "ADD_MOTOR_DATA";
export const GET_MOTOR_DATA = "GET_MOTOR_DATA";
export const GET_MOTOR_DATA_BY_ID = "GET_MOTOR_DATA_BY_ID";
